use anyhow::{Context, Result, bail};
use colored::Colorize;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

use crate::git;

const HOOK_NAME: &str = "prepare-commit-msg";
const HOOK_MARKER: &str = "forged:auto-generated";

const HOOK_SCRIPT: &str = r#"#!/bin/sh
# forged:auto-generated — do not edit
# AI-powered commit message generator
COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Only run for regular commits (not merge, squash, amend, etc.)
if [ -z "$COMMIT_SOURCE" ] || [ "$COMMIT_SOURCE" = "message" ]; then
    if command -v forged >/dev/null 2>&1; then
        forged --hook "$COMMIT_MSG_FILE" || true
    fi
fi
"#;

/// Get the path to the hooks directory for the current git repo.
fn hooks_dir() -> Result<PathBuf> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--git-dir"])
        .output()
        .context("Failed to run git rev-parse")?;

    if !output.status.success() {
        bail!("Not inside a git repository");
    }

    let git_dir = String::from_utf8_lossy(&output.stdout).trim().to_string();
    Ok(PathBuf::from(git_dir).join("hooks"))
}

/// Check if a hook file was generated by forged.
fn is_forged_hook(path: &PathBuf) -> bool {
    fs::read_to_string(path)
        .map(|content| content.contains(HOOK_MARKER))
        .unwrap_or(false)
}

/// Get the hook script content.
pub fn hook_script() -> &'static str {
    HOOK_SCRIPT
}

/// Install the prepare-commit-msg hook in the current git repo.
pub fn install(force: bool) -> Result<()> {
    git::assert_git_repo()?;

    let hooks = hooks_dir()?;
    fs::create_dir_all(&hooks).context("Failed to create hooks directory")?;

    let hook_path = hooks.join(HOOK_NAME);

    if hook_path.exists() && !is_forged_hook(&hook_path) && !force {
        bail!(
            "A {} hook already exists and was not created by forged.\n  \
             Use {} to overwrite it.",
            HOOK_NAME,
            "--force".bold()
        );
    }

    fs::write(&hook_path, HOOK_SCRIPT).context("Failed to write hook file")?;
    fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))
        .context("Failed to set hook permissions")?;

    println!(
        "{} Hook installed in .git/hooks/{}",
        "✔".green(),
        HOOK_NAME
    );
    println!(
        "  {} Now {} will auto-generate commit messages.",
        "→".dimmed(),
        "git commit".bold()
    );

    Ok(())
}

/// Remove the prepare-commit-msg hook if it was installed by forged.
pub fn uninstall(force: bool) -> Result<()> {
    git::assert_git_repo()?;

    let hooks = hooks_dir()?;
    let hook_path = hooks.join(HOOK_NAME);

    if !hook_path.exists() {
        println!("{} No {} hook found.", "⚠".yellow(), HOOK_NAME);
        return Ok(());
    }

    if !is_forged_hook(&hook_path) && !force {
        bail!(
            "The {} hook was not created by forged.\n  \
             Use {} to remove it anyway.",
            HOOK_NAME,
            "--force".bold()
        );
    }

    fs::remove_file(&hook_path).context("Failed to remove hook file")?;

    println!("{} Hook removed from .git/hooks/{}", "✔".green(), HOOK_NAME);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hook_script_contains_marker() {
        assert!(HOOK_SCRIPT.contains(HOOK_MARKER));
    }

    #[test]
    fn test_hook_script_is_valid_shell() {
        assert!(HOOK_SCRIPT.starts_with("#!/bin/sh"));
    }

    #[test]
    fn test_hook_script_calls_forged() {
        assert!(HOOK_SCRIPT.contains("forged --hook"));
    }

    #[test]
    fn test_hook_script_fail_safe() {
        // || true ensures forged failures don't block the commit
        assert!(HOOK_SCRIPT.contains("|| true"));
    }

    #[test]
    fn test_hook_script_skips_merge_and_amend() {
        // Should only run when COMMIT_SOURCE is empty or "message"
        assert!(HOOK_SCRIPT.contains("[ -z \"$COMMIT_SOURCE\" ]"));
        assert!(HOOK_SCRIPT.contains("\"$COMMIT_SOURCE\" = \"message\""));
    }

    #[test]
    fn test_is_forged_hook_detects_marker() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hook");

        // Forged hook
        fs::write(&path, HOOK_SCRIPT).unwrap();
        assert!(is_forged_hook(&path.to_path_buf()));

        // Non-forged hook
        fs::write(&path, "#!/bin/sh\necho hello\n").unwrap();
        assert!(!is_forged_hook(&path.to_path_buf()));

        // Non-existent
        let missing = dir.path().join("missing");
        assert!(!is_forged_hook(&missing.to_path_buf()));
    }
}
